export const allGenres = [
  'All',
  'Action & Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Documentary',
  'Family',
  'Kids',
  'Mystery',
  'Reality',
  'Sci-Fi & Fantasy',
  'Talk',
  'War & Politics',
  'Western',
];

export const allGenresForMovies = [
  'All',
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'Thriller',
  'War',
  'Western',
];
