export const allGenres = [
  'All',
  'Action & Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Documentary',
  'Family',
  'Kids',
  'Mystery',
  'Reality',
  'Sci-Fi & Fantasy',
  'Talk',
  'War & Politics',
  'Western',
];

export const allGenresForMovies = [
  'All',
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'Thriller',
  'War',
  'Western',
];

// Mapping für die Anzeige
export const genreDisplayNames: Record<string, string> = {
  All: 'Overall',
  'Action & Adventure': 'Action & Adventure',
  Animation: 'Animation',
  Comedy: 'Comedy',
  Crime: 'Crime',
  Drama: 'Drama',
  Documentary: 'Documentary',
  Family: 'Family',
  Kids: 'Kids',
  Mystery: 'Mystery',
  Reality: 'Reality',
  'Sci-Fi & Fantasy': 'Sci-Fi & Fantasy',
  Talk: 'Talk',
  'War & Politics': 'War & Politics',
  Western: 'Western',
};
