export const PET_CONFIG = {
  // Pet limits
  MAX_PETS: 2,
  SECOND_PET_LEVEL_REQUIREMENT: 15,

  // Feeding
  HUNGER_DECREASE_PER_FEED: 30,
  HAPPINESS_INCREASE_PER_FEED: 10,

  // Playing
  HAPPINESS_INCREASE_PER_PLAY: 20,
  HUNGER_INCREASE_PER_PLAY: 10,

  // XP & Leveling
  BASE_XP_PER_EPISODE: 10,
  GENRE_MATCH_XP_PER_EPISODE: 20,
  GENRE_MATCH_HAPPINESS_BONUS: 5,
  XP_PER_LEVEL: 100,

  // Initial values
  INITIAL_HUNGER: 50,
  INITIAL_HAPPINESS: 75,

  // Revival
  REVIVAL_HUNGER: 50,
  REVIVAL_HAPPINESS: 50,

  // Death thresholds
  HUNGER_DEATH_THRESHOLD: 100,
  HAPPINESS_DEATH_THRESHOLD: 0,
  NEGLECT_DAYS_THRESHOLD: 14,
  HIGH_HUNGER_HAPPINESS_PENALTY: 3,
  HIGH_HUNGER_THRESHOLD: 80,

  // Accessories
  CROWN_LEVEL_REQUIREMENT: 10,
  SANTA_HAT_MONTH: 12,
  SUNGLASSES_MONTHS: [6, 7, 8],

  // Achievement thresholds
  SILVER_COLOR_SERIES_THRESHOLD: 25,
  GOLD_COLOR_SERIES_THRESHOLD: 50,
  RAINBOW_COLOR_SERIES_THRESHOLD: 100,
  GALAXY_PATTERN_EPISODES_THRESHOLD: 200,
} as const;
