export const genreMenuItems = [
  { value: 'All', label: 'All' },
  { value: 'Action & Adventure', label: 'Action & Adventure' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Comedy', label: 'Comedy' },
  { value: 'Crime', label: 'Crime' },
  { value: 'Drama', label: 'Drama' },
  { value: 'Documentary', label: 'Documentary' },
  { value: 'Family', label: 'Family' },
  { value: 'Kids', label: 'Kids' },
  { value: 'Mystery', label: 'Mystery' },
  { value: 'Reality', label: 'Reality' },
  { value: 'Sci-Fi & Fantasy', label: 'Sci-Fi & Fantasy' },
  { value: 'Talk', label: 'Talk' },
  { value: 'War & Politics', label: 'War & Politics' },
  { value: 'Western', label: 'Western' },
  { value: 'Ohne Bewertung', label: 'Ohne Bewertung' },
  { value: 'Neue Episoden', label: 'Neue Episoden' },
  { value: 'Zuletzt Hinzugefügt', label: 'Zuletzt Hinzugefügt' },
];

export const providerMenuItems = [
  { value: 'All', label: 'Alle' },
  { value: 'Amazon Prime Video', label: 'Prime Video' },
  { value: 'Animation Digital Network', label: 'ADN' },
  { value: 'Apple TV Plus', label: 'AppleTV+' },
  { value: 'Crunchyroll', label: 'Crunchyroll' },
  { value: 'Disney Plus', label: 'Disney+' },
  { value: 'Freevee', label: 'Freevee' },
  { value: 'Joyn Plus', label: 'Joyn+' },
  { value: 'MagentaTV', label: 'MagentaTV' },
  { value: 'Netflix', label: 'Netflix' },
  { value: 'Paramount Plus', label: 'Paramount+' },
  { value: 'RTL+', label: 'RTL+' },
  { value: 'WOW', label: 'WOW' },
];
