import {
  AccountBalance,
  AutoFixHigh,
  Brush,
  CameraAlt,
  ChildCare,
  DarkMode,
  EmojiEmotions,
  Explore,
  FamilyRestroom,
  Favorite,
  Fingerprint,
  HeartBroken,
  HistoryEdu,
  Landscape,
  LocalFireDepartment,
  Mic,
  MilitaryTech,
  Movie,
  MusicNote,
  Newspaper,
  Psychology,
  RocketLaunch,
  Search,
  TheaterComedy,
  Tv,
  Videocam,
} from '@mui/icons-material';
import type { SvgIconComponent } from '@mui/icons-material';
import { createElement, type CSSProperties } from 'react';

// Schlüssel klein geschrieben; deutsche und englische TMDB-Genre-Namen.
const ICONS: Record<string, SvgIconComponent> = {
  action: LocalFireDepartment,
  'action & adventure': LocalFireDepartment,
  adventure: Explore,
  abenteuer: Explore,
  animation: Brush,
  comedy: EmojiEmotions,
  komödie: EmojiEmotions,
  crime: Fingerprint,
  krimi: Fingerprint,
  documentary: Videocam,
  dokumentarfilm: Videocam,
  dokumentation: Videocam,
  drama: TheaterComedy,
  family: FamilyRestroom,
  familie: FamilyRestroom,
  fantasy: AutoFixHigh,
  history: HistoryEdu,
  historie: HistoryEdu,
  horror: DarkMode,
  music: MusicNote,
  musik: MusicNote,
  mystery: Search,
  romance: Favorite,
  liebesfilm: Favorite,
  romantik: Favorite,
  'science fiction': RocketLaunch,
  'sci-fi & fantasy': RocketLaunch,
  'tv movie': Tv,
  'tv-film': Tv,
  thriller: Psychology,
  war: MilitaryTech,
  kriegsfilm: MilitaryTech,
  'war & politics': AccountBalance,
  'krieg & politik': AccountBalance,
  western: Landscape,
  kids: ChildCare,
  kinder: ChildCare,
  news: Newspaper,
  nachrichten: Newspaper,
  reality: CameraAlt,
  soap: HeartBroken,
  talk: Mic,
};

const genreIconFor = (genre: string): SvgIconComponent =>
  ICONS[genre.trim().toLowerCase()] ?? Movie;

export const GenreIcon = ({ genre, style }: { genre: string; style?: CSSProperties }) =>
  createElement(genreIconFor(genre), { style });
