import type { Badge } from './badgeDefinitions';
import { t } from '../../services/i18n';

const RARITY_COLORS = {
  common: '#8BC34A', // Frisches Grün
  rare: '#2196F3', // Lebendiges Blau
  epic: '#9C27B0', // Majestätisches Lila
  legendary: '#FF5722', // Kraftvolles Orange-Rot
};

export const BADGE_DEFINITIONS: Badge[] = [
  // BINGE BADGES
  {
    id: 'binge_bronze',
    category: 'binge',
    tier: 'bronze',
    name: t('Snack-Session'),
    description: t('3 Episoden hintereinander geschaut'),
    color: RARITY_COLORS.common,
    requirements: { episodes: 3, timeframe: '10hours' },
    rarity: 'common',
  },
  {
    id: 'binge_bronze_plus',
    category: 'binge',
    tier: 'bronze',
    name: t('Appetit-Anreger'),
    description: t('5 Episoden hintereinander geschaut'),
    color: RARITY_COLORS.common,
    requirements: { episodes: 5, timeframe: '10hours' },
    rarity: 'common',
  },
  {
    id: 'binge_silver',
    category: 'binge',
    tier: 'silver',
    name: t('Couch-Potato'),
    description: t('8 Episoden hintereinander geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { episodes: 8, timeframe: '10hours' },
    rarity: 'rare',
  },
  {
    id: 'binge_silver_plus',
    category: 'binge',
    tier: 'silver',
    name: t('Serien-Schnürer'),
    description: t('10 Episoden hintereinander geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { episodes: 10, timeframe: '10hours' },
    rarity: 'rare',
  },
  {
    id: 'binge_gold',
    category: 'binge',
    tier: 'gold',
    name: t('Binge-Meister'),
    description: t('15 Episoden an einem Tag geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 15, timeframe: '1day' },
    rarity: 'epic',
  },
  {
    id: 'binge_gold_plus',
    category: 'binge',
    tier: 'gold',
    name: t('Binge-König'),
    description: t('20 Episoden an einem Tag geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 20, timeframe: '1day' },
    rarity: 'epic',
  },
  {
    id: 'binge_platinum',
    category: 'binge',
    tier: 'platinum',
    name: t('Binge-Monster'),
    description: t('25 Episoden an einem Tag verschlungen'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 25, timeframe: '1day' },
    rarity: 'epic',
  },
  {
    id: 'binge_diamond',
    category: 'binge',
    tier: 'diamond',
    name: t('Binge-Gott'),
    description: t('35 Episoden in zwei Tagen geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 35, timeframe: '2days' },
    rarity: 'legendary',
  },
  {
    id: 'binge_diamond_plus',
    category: 'binge',
    tier: 'diamond',
    name: t('Binge-Titan'),
    description: t('50 Episoden in zwei Tagen geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 50, timeframe: '2days' },
    rarity: 'legendary',
  },

  // QUICKWATCH BADGES
  {
    id: 'quickwatch_bronze',
    category: 'quickwatch',
    tier: 'bronze',
    name: t('Früher Vogel'),
    description: t('3 Episoden am Veröffentlichungstag geschaut'),
    color: RARITY_COLORS.common,
    requirements: { episodes: 3 },
    rarity: 'common',
  },
  {
    id: 'quickwatch_silver',
    category: 'quickwatch',
    tier: 'silver',
    name: t('Day One Fan'),
    description: t('8 Episoden am Veröffentlichungstag geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { episodes: 8 },
    rarity: 'rare',
  },
  {
    id: 'quickwatch_gold',
    category: 'quickwatch',
    tier: 'gold',
    name: t('Release Hunter'),
    description: t('15 Episoden am Veröffentlichungstag geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 15 },
    rarity: 'epic',
  },
  {
    id: 'quickwatch_platinum',
    category: 'quickwatch',
    tier: 'platinum',
    name: t('Release Predator'),
    description: t('25 Episoden am Veröffentlichungstag geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 25 },
    rarity: 'legendary',
  },
  {
    id: 'quickwatch_diamond',
    category: 'quickwatch',
    tier: 'diamond',
    name: t('Day Zero Destroyer'),
    description: t('40 Episoden am Veröffentlichungstag geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 40 },
    rarity: 'legendary',
  },

  // MARATHON BADGES
  {
    id: 'marathon_bronze',
    category: 'marathon',
    tier: 'bronze',
    name: t('Serien-Fan'),
    description: t('15 Episoden in einer Woche geschaut'),
    color: RARITY_COLORS.common,
    requirements: { episodes: 15, timeframe: '1week' },
    rarity: 'common',
  },
  {
    id: 'marathon_silver',
    category: 'marathon',
    tier: 'silver',
    name: t('Wochenend-Warrior'),
    description: t('25 Episoden in einer Woche geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { episodes: 25, timeframe: '1week' },
    rarity: 'rare',
  },
  {
    id: 'marathon_gold',
    category: 'marathon',
    tier: 'gold',
    name: t('Marathon-Meister'),
    description: t('40 Episoden in einer Woche geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 40, timeframe: '1week' },
    rarity: 'epic',
  },
  {
    id: 'marathon_platinum',
    category: 'marathon',
    tier: 'platinum',
    name: t('Wochenend-Titan'),
    description: t('60 Episoden in einer Woche geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 60, timeframe: '1week' },
    rarity: 'legendary',
  },
  {
    id: 'marathon_diamond',
    category: 'marathon',
    tier: 'diamond',
    name: t('Serien-Vernichter'),
    description: t('80 Episoden in einer Woche geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 80, timeframe: '1week' },
    rarity: 'legendary',
  },

  // STREAK BADGES
  {
    id: 'streak_bronze',
    category: 'streak',
    tier: 'bronze',
    name: t('Gewohnheitstier'),
    description: t('7 Tage in Folge Serien geschaut'),
    color: RARITY_COLORS.common,
    requirements: { days: 7 },
    rarity: 'common',
  },
  {
    id: 'streak_silver',
    category: 'streak',
    tier: 'silver',
    name: t('Serien-Routine'),
    description: t('14 Tage in Folge Serien geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { days: 14 },
    rarity: 'rare',
  },
  {
    id: 'streak_gold',
    category: 'streak',
    tier: 'gold',
    name: t('Unaufhaltsam'),
    description: t('30 Tage in Folge Serien geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { days: 30 },
    rarity: 'epic',
  },
  {
    id: 'streak_platinum',
    category: 'streak',
    tier: 'platinum',
    name: t('Serien-Süchtig'),
    description: t('60 Tage in Folge Serien geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { days: 60 },
    rarity: 'legendary',
  },
  {
    id: 'streak_diamond',
    category: 'streak',
    tier: 'diamond',
    name: t('Ewige Flamme'),
    description: t('100 Tage in Folge Serien geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { days: 100 },
    rarity: 'legendary',
  },

  // REWATCH BADGES
  {
    id: 'rewatch_bronze',
    category: 'rewatch',
    tier: 'bronze',
    name: t('Zweiter Blick'),
    description: t('5 Episoden als Rewatch geschaut'),
    color: RARITY_COLORS.common,
    requirements: { episodes: 5 },
    rarity: 'common',
  },
  {
    id: 'rewatch_silver',
    category: 'rewatch',
    tier: 'silver',
    name: t('Nostalgie-Fan'),
    description: t('15 Episoden als Rewatch geschaut'),
    color: RARITY_COLORS.rare,
    requirements: { episodes: 15 },
    rarity: 'rare',
  },
  {
    id: 'rewatch_gold',
    category: 'rewatch',
    tier: 'gold',
    name: t('Rewatch-König'),
    description: t('30 Episoden als Rewatch geschaut'),
    color: RARITY_COLORS.epic,
    requirements: { episodes: 30 },
    rarity: 'epic',
  },
  {
    id: 'rewatch_platinum',
    category: 'rewatch',
    tier: 'platinum',
    name: t('Nostalgie-Experte'),
    description: t('60 Episoden als Rewatch geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 60 },
    rarity: 'legendary',
  },
  {
    id: 'rewatch_diamond',
    category: 'rewatch',
    tier: 'diamond',
    name: t('Zeitreisender'),
    description: t('100 Episoden als Rewatch geschaut'),
    color: RARITY_COLORS.legendary,
    requirements: { episodes: 100 },
    rarity: 'legendary',
  },

  // EXPLORER BADGES
  {
    id: 'explorer_bronze',
    category: 'series_explorer',
    tier: 'bronze',
    name: t('Entdecker'),
    description: t('50 verschiedene Serien angefangen'),
    color: RARITY_COLORS.common,
    requirements: { series: 50 },
    rarity: 'common',
  },
  {
    id: 'explorer_silver',
    category: 'series_explorer',
    tier: 'silver',
    name: t('Serien-Scout'),
    description: t('100 verschiedene Serien angefangen'),
    color: RARITY_COLORS.rare,
    requirements: { series: 100 },
    rarity: 'rare',
  },
  {
    id: 'explorer_gold',
    category: 'series_explorer',
    tier: 'gold',
    name: t('Genre-Meister'),
    description: t('200 verschiedene Serien angefangen'),
    color: RARITY_COLORS.epic,
    requirements: { series: 200 },
    rarity: 'epic',
  },
  {
    id: 'explorer_platinum',
    category: 'series_explorer',
    tier: 'platinum',
    name: t('Serien-Weltreisender'),
    description: t('300 verschiedene Serien angefangen'),
    color: RARITY_COLORS.legendary,
    requirements: { series: 300 },
    rarity: 'legendary',
  },
  {
    id: 'explorer_diamond',
    category: 'series_explorer',
    tier: 'diamond',
    name: t('Serien-Universum'),
    description: t('500 verschiedene Serien angefangen'),
    color: RARITY_COLORS.legendary,
    requirements: { series: 500 },
    rarity: 'legendary',
  },
  {
    id: 'explorer_mythic',
    category: 'series_explorer',
    tier: 'diamond',
    name: t('Omnipräsenter Explorer'),
    description: t('750+ verschiedene Serien angefangen'),
    color: RARITY_COLORS.legendary,
    requirements: { series: 750 },
    rarity: 'legendary',
  },

  // COLLECTOR BADGES
  {
    id: 'collector_bronze',
    category: 'collector',
    tier: 'bronze',
    name: t('Kritiker'),
    description: t('50 Serien oder Filme bewertet'),
    color: RARITY_COLORS.common,
    requirements: { ratings: 50 },
    rarity: 'common',
  },
  {
    id: 'collector_silver',
    category: 'collector',
    tier: 'silver',
    name: t('Bewertungs-Experte'),
    description: t('150 Serien oder Filme bewertet'),
    color: RARITY_COLORS.rare,
    requirements: { ratings: 150 },
    rarity: 'rare',
  },
  {
    id: 'collector_gold',
    category: 'collector',
    tier: 'gold',
    name: t('Rating-Meister'),
    description: t('300 Serien oder Filme bewertet'),
    color: RARITY_COLORS.epic,
    requirements: { ratings: 300 },
    rarity: 'epic',
  },
  {
    id: 'collector_platinum',
    category: 'collector',
    tier: 'platinum',
    name: t('Bewertungs-Gott'),
    description: t('500 Serien oder Filme bewertet'),
    color: RARITY_COLORS.legendary,
    requirements: { ratings: 500 },
    rarity: 'legendary',
  },
  {
    id: 'collector_diamond',
    category: 'collector',
    tier: 'diamond',
    name: t('Kritiker-Legende'),
    description: t('750 Serien oder Filme bewertet'),
    color: RARITY_COLORS.legendary,
    requirements: { ratings: 750 },
    rarity: 'legendary',
  },
  {
    id: 'collector_mythic',
    category: 'collector',
    tier: 'diamond',
    name: t('Allmächtiger Kritiker'),
    description: t('1000+ Serien oder Filme bewertet'),
    color: RARITY_COLORS.legendary,
    requirements: { ratings: 1000 },
    rarity: 'legendary',
  },

  // SOCIAL BADGES
  {
    id: 'social_bronze',
    category: 'social',
    tier: 'bronze',
    name: t('Gesellig'),
    description: t('3 Freunde hinzugefügt'),
    color: RARITY_COLORS.common,
    requirements: { friends: 3 },
    rarity: 'common',
  },
  {
    id: 'social_silver',
    category: 'social',
    tier: 'silver',
    name: t('Serien-Buddy'),
    description: t('8 Freunde hinzugefügt'),
    color: RARITY_COLORS.rare,
    requirements: { friends: 8 },
    rarity: 'rare',
  },
  {
    id: 'social_gold',
    category: 'social',
    tier: 'gold',
    name: t('Community-Leader'),
    description: t('15 Freunde hinzugefügt'),
    color: RARITY_COLORS.epic,
    requirements: { friends: 15 },
    rarity: 'epic',
  },
  {
    id: 'social_platinum',
    category: 'social',
    tier: 'platinum',
    name: t('Netzwerk-Guru'),
    description: t('25 Freunde hinzugefügt'),
    color: RARITY_COLORS.legendary,
    requirements: { friends: 25 },
    rarity: 'legendary',
  },
  {
    id: 'social_diamond',
    category: 'social',
    tier: 'diamond',
    name: t('Serien-Influencer'),
    description: t('50 Freunde hinzugefügt'),
    color: RARITY_COLORS.legendary,
    requirements: { friends: 50 },
    rarity: 'legendary',
  },
];
